### model
model_name_or_path: /data/pretrain_dir/Llama-3.1 
adapter_name_or_path: /data/fxy/ecpo/fine-tuning/sft/Book/lr5.0e-5_epochs3.0
reward_model: /data/fxy/ecpo/fine-tuning/reward

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: amazon_book_ppo
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/fxy/ecpo/fine-tuning/ppo/Book/lr1.0e-5_epochs3.0
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9